name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
     # -
      #  name: Build and push
       # uses: docker/build-push-action@v2
        #with:
         # context: .
          #file: ./Dockerfile
          #push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sampledemo:latest
      
      -
        name: Scripts
        run:
           docker build -t app .
           docker login -u kavyakarr -p a8df4058-4222-46b1-8cbd-a3bfdb1fe0a8
           docker tag app kavyakarr/testrepo
           docker push kavyakarr/testrepo
